slice_name: Source period and pipeline provenance (full source)
description: ''
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 7__table
  viz_type: table
  time_range: No filter
  granularity_sqla: null
  time_grain_sqla: P1D
  adhoc_filters: []
  row_limit: 10000
  metrics: []
  groupby: []
  color_scheme: supersetColors
  show_legend: true
  legendType: scroll
  legendOrientation: top
  rich_tooltip: true
  tooltipTimeFormat: '%Y-%m-%d %H:%M'
  y_axis_format: .2f
  x_axis_time_format: '%b %d'
  truncateYAxis: false
  query_mode: raw
  all_columns:
  - source_name
  - first_observation
  - last_observation
  - pipeline_loaded_at
  - source_sha256
  - timestamp_context
  page_length: 10
  include_search: false
  order_desc: false
  table_timestamp_format: '%Y-%m-%d %H:%M'
  allow_render_html: false
  slice_id: 13
query_context: '{"datasource": {"id": 7, "type": "table"}, "force": true, "queries":
  [{"time_range": "No filter", "granularity": null, "filters": [], "metrics": [],
  "columns": ["source_name", "first_observation", "last_observation", "pipeline_loaded_at",
  "source_sha256", "timestamp_context"], "row_limit": 10000, "orderby": [], "is_timeseries":
  false, "extras": {"time_grain_sqla": "P1D", "having": "", "where": ""}}], "form_data":
  {"datasource": "7__table", "viz_type": "table", "time_range": "No filter", "granularity_sqla":
  null, "time_grain_sqla": "P1D", "adhoc_filters": [], "row_limit": 10000, "metrics":
  [], "groupby": [], "color_scheme": "supersetColors", "show_legend": true, "legendType":
  "scroll", "legendOrientation": "top", "rich_tooltip": true, "tooltipTimeFormat":
  "%Y-%m-%d %H:%M", "y_axis_format": ".2f", "x_axis_time_format": "%b %d", "truncateYAxis":
  false, "query_mode": "raw", "all_columns": ["source_name", "first_observation",
  "last_observation", "pipeline_loaded_at", "source_sha256", "timestamp_context"],
  "page_length": 10, "include_search": false, "order_desc": false, "table_timestamp_format":
  "%Y-%m-%d %H:%M", "allow_render_html": false, "slice_id": 13}, "result_format":
  "json", "result_type": "full"}'
cache_timeout: 0
uuid: 6a04722b-02d4-495e-98c2-f3d1d4aa29ac
version: 1.0.0
dataset_uuid: d6b7d98f-83be-47cc-ba03-280d28c9a7e7
